spring:
  datasource:
    url: jdbc:mysql://39.108.236.13:3306/rtdbinfo_advs?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat

#多数据源情况的配置
guns:
  muti-datasource:
    open: true
    url: jdbc:mysql://39.108.236.13:3306/rtdbinfo_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz


  # 第三个数据源
  third-datasource:
    url: jdbc:mysql://39.108.236.13:3306/?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    thirdDataSourceName: dataSourceAll
